from litesoph.simulations.esmd import (GROUND_STATE, RT_TDDFT_DELTA, RT_TDDFT_LASER,
                                        SPECTRUM, TCM, MO_POPULATION_CORRELATION)

SHOW_PAGE_EVENT = '<<Show{}Page>>'
SHOW_WORK_MANAGER_PAGE = SHOW_PAGE_EVENT.format('WorkManager')
SHOW_GROUND_STATE_PAGE = SHOW_PAGE_EVENT.format(GROUND_STATE)
SHOW_RT_TDDFT_DELTA_PAGE = SHOW_PAGE_EVENT.format(RT_TDDFT_DELTA)  
SHOW_RT_TDDFT_LASER_PAGE = SHOW_PAGE_EVENT.format(RT_TDDFT_LASER)
SHOW_SPECTRUM_PAGE = SHOW_PAGE_EVENT.format(SPECTRUM)
SHOW_TCM_PAGE = SHOW_PAGE_EVENT.format(TCM)
SHOW_MO_POPULATION_CORRELATION_PAGE = SHOW_PAGE_EVENT.format(MO_POPULATION_CORRELATION)



GET_MOLECULE = '<<GetMolecule>>'
VISUALIZE_MOLECULE = '<<VisualizeMolecule>>'
CREATE_NEW_PROJECT = '<<CreateNewProject>>' 
CREATE_PROJECT_WINDOW = '<<create_filemenu_project>>'

OPEN_PROJECT = '<<OpenExistingProject>>'
ON_PROCEED = '<<SelectProceed>>' 
ON_BACK_BUTTON = '<<ClickBackButton>>'
REFRESH_CONFIG = '<<RefreshConfig>>'