
GROUND_STATE = 'ground_state'
RT_TDDFT_DELTA = 'rt_tddft_delta'
RT_TDDFT_LASER = 'rt_tddft_laser'
SPECTRUM = 'spectrum'
TCM = 'tcm'
MO_POPULATION_CORRELATION = 'mo_population_correlation'


SHOW_PAGE_EVENT = '<<Show{}Page>>'
SHOW_WORK_MANAGER_PAGE = SHOW_PAGE_EVENT.format('WorkManager')
SHOW_GROUND_STATE_PAGE = SHOW_PAGE_EVENT.format(GROUND_STATE)
SHOW_RT_TDDFT_DELTA_PAGE = SHOW_PAGE_EVENT.format(RT_TDDFT_DELTA)  
SHOW_RT_TDDFT_LASER_PAGE = SHOW_PAGE_EVENT.format(RT_TDDFT_LASER)
SHOW_SPECTRUM_PAGE = SHOW_PAGE_EVENT.format(SPECTRUM)
SHOW_TCM_PAGE = SHOW_PAGE_EVENT.format(TCM)
SHOW_MO_POPULATION_CORRELATION_PAGE = SHOW_PAGE_EVENT.format(MO_POPULATION_CORRELATION)



GET_MOLECULE = '<<GetMolecule>>'
VISUALIZE_MOLECULE = '<<VisualizeMolecule>>'
CREATE_NEW_PROJECT = '<<CreateNewProject>>' 
OPEN_PROJECT = '<<OpenExistingProject>>'
ON_PROCEED = '<<SelectProceed>>' 
ON_BACK_BUTTON = '<<ClickBackButton>>'
REFRESH_CONFIG = '<<RefreshConfig>>'